on: [push]

jobs:
  update_github_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir public

    - uses: docker://pandoc/core
      with:
        args: README.md --template template.html -o public/index.html
 
    - run: |
        sudo apt install -y xvfb libfontconfig wkhtmltopdf fonts-noto-color-emoji
        xvfb-run -a -s "-screen 0 640x480x16" wkhtmltopdf public/index.html public/quarno.pdf

    - uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: quarno/quarno.github.io
        publish_branch: master
        publish_dir: ./public
        cname: quarno.xyz
