name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: md to tex
        uses: docker://pandoc/core
        with:
          args: cv.md -f markdown+latex_macros -o cv.tex
      
      - name: tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
          post_compile: mv cv.pdf public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: netlify
          publish_dir: ./public
          enable_jekyll: true
