on: [push]

jobs:
  update_github_pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - run: |
        sudo apt install -y make pandoc weasyprint
        make all

    - uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: quarno/quarno.github.io
        publish_branch: master
        publish_dir: ./public
        cname: quarno.xyz
